#!/usr/local/munkireport/munkireport-python3

import os
import subprocess
import sys
import glob
import plistlib
import time

sys.path.insert(0, '/usr/local/munkireport')

from munkilib import FoundationPlist

def get_warranty_plist():

    plists = glob.glob('/Users/*/Library/Application Support/com.apple.NewDeviceOutreach/*_Warranty.plist')

    # Check if we have data
    if len(plists) == 0:
        return ""

    machine_model = get_machine_model()

    matched_plists = []

    # Check each plist to match plist to the current Mac
    # Not the best as Apple does not store the serial number
    # in the plist in a usable way, so we match on machine model
    for plist in plists:

        warranty_plist_data = FoundationPlist.readPlist(plist)
        if "deviceInfo" in warranty_plist_data and "deviceImageUrl" in warranty_plist_data["deviceInfo"]:
            if machine_model in warranty_plist_data["deviceInfo"]["deviceImageUrl"]:
                matched_plists.append(plist)

    # Get the latest touched plist, if matched to machine model
    if matched_plists is not []:
        latest_plist = max(matched_plists, key=os.path.getctime)
    else:
        latest_plist = max(plists, key=os.path.getctime)

    return latest_plist

def get_machine_model():

    cmd = ["/usr/sbin/sysctl","-n","hw.model"]
    proc = subprocess.Popen(cmd, shell=False, bufsize=-1,
                            stdin=subprocess.PIPE,
                            stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    (output, unused_error) = proc.communicate()

    return output.decode().strip()

def process_warranty(warranty_plist):

    pl = FoundationPlist.readPlist(warranty_plist)
    out = {}
    for item in pl:
        # Extract username from path by removing everything up to and including /Users/ and
        # everything from /Library/ onwards
        path_parts = warranty_plist.split('/Users/', 1)
        if len(path_parts) > 1:
            username_and_rest = path_parts[1]
            username = username_and_rest.split('/Library/', 1)[0]
            out['prefpath'] = username
        
        if item == 'coverageEndDate':
            out['coverage_end_date'] = str(pl[item])
        elif item == 'coverageLocalizedDesc':
            out['status'] = pl[item].replace("+", "")
        elif item == 'covered':
            out['covered'] = to_bool(pl[item])
        elif item == 'coverageTypeCode':
            out['coverage_type_code'] = pl[item]

    # Set Limited Warranty or AppleCare
    if "coverage_type_code" in out and out['coverage_type_code'] == "LI" and "status" in out and "AppleCare" not in out['status']:
        out['status'] = "Limited Warranty"

    # Check if our coverage has expired
    if "covered" in out and out['covered'] == 0:
        out['status'] = "Expired"

    return out

def get_icloud_state():

    # We're checking for an iCloud log in because Apple requires this for automated on Mac warranty lookups
    plists = glob.glob('/Users/*/Library/Preferences/MobileMeAccounts.plist')

    # Check if we have data
    if len(plists) == 0:
        return 0
    else:
        return 1

def to_bool(s):
    if s == True:
        return 1
    else:
        return 0


def main():
    """Main"""

    result = dict()

    # Get the latest warranty plist
    warranty_plist = get_warranty_plist()
    if warranty_plist != "":
        result = process_warranty(warranty_plist)

    result["icloud_logged_in"] = get_icloud_state()

    # Write warranty result to cache
    cachedir = '%s/cache' % os.path.dirname(os.path.realpath(__file__))
    output_plist = os.path.join(cachedir, 'warranty.plist')

    # Check if we need to do weekly re-process of warranty info
    if os.path.isfile(output_plist):
        with open(output_plist, 'rb') as infile:
            cache_plist = plistlib.load(infile)
        infile.close()

        # Check if we need to add, update, or keep the timestamp of the last run
        if "timestamp" not in cache_plist:
            result["timestamp"] = str(int(time.time()))
        elif "timestamp" in cache_plist and int(time.time()) > int(cache_plist['timestamp'])+604800:
            result["timestamp"] = str(int(time.time()))
        else:
            result["timestamp"] = str(cache_plist['timestamp'])
    else:
        result["timestamp"] = str(int(time.time()))

    FoundationPlist.writePlist(result, output_plist)

if __name__ == "__main__":
    main()
